MORBIDITY_PK_PREFIX = 'MR#'
MORBIDITY_SK_PREFIX = 'TEST#'
USERS_PK_PREFIX = 'LOGIN#'
USERS_SK_PREFIX = 'USER#'
RECIPE_PK_PREFIX = 'RECIPE#'
RECIPE_PK_PREFIX = 'RID#'
MORBIDITY_INFO = 'Morbidity'
USERS_SK_PREFIX = {'Dietician' : 'DT','Patient' :'PT'}